name: API Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v3

      # 2. 列出当前工作目录文件，确认 Postman collection 存在
      - name: List files in workspace
        run: ls -l

      # 3. 安装 Node.js（newman 依赖 Node.js）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 4. 全局安装 newman
      - name: Install Newman
        run: npm install -g newman

      # 5. 运行 newman，执行接口测试并输出 junit 格式结果
      - name: Run Newman tests
        run: newman run todo-api.postman_collection.json --reporters cli,junit --reporter-junit-export results.xml
