name: Todo API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v3

      # 2. 确认文件存在，打印目录
      - name: List files in workspace
        run: ls -l

      # 3. 安装 Node.js，Newman 依赖它
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 4. 全局安装 Newman
      - name: Install Newman
        run: npm install -g newman

      # 5. 运行 Newman 测试
      - name: Run Newman tests
        run: newman run todo-api.postman_collection.json --reporters cli,junit --reporter-junit-export results.xml
