name: Todo API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in workspace
        run: ls -l

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman and HTML reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Newman tests with HTML report
        run: |
          newman run todo-api.postman_collection.json -r cli,htmlextra --reporter-htmlextra-export report.html --suppress-exit-code

      - name: Upload Newman HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: report.html
