name: Todo List API Tests (Newman + CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Newman and HTML reporter
      run: |
        npm install -g newman newman-reporter-htmlextra

    - name: Run Postman Collection with HTML report
      run: |
        newman run "Todo API Collection.postman_collection.json" \
          -r htmlextra \
          --reporter-htmlextra-export report.html

    - name: Upload Newman HTML report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: report.html
